Refactor CI workflow to remove redundant environment variable steps
- Removed duplicate steps for setting and loading environment variables from .env.ci in the CI workflow, streamlining the process.
- Maintained the necessary steps for environment management during E2E tests, ensuring clarity and efficiency in the workflow.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -47,6 +47,18 @@ jobs:
       - name: Run Integration Tests
         run: go test -v ./tests/integration/...
 
+      - name: Set environment variable for CI
+        run: echo "MY_ENV_FILE=.env.ci" >> $GITHUB_ENV
+
+      - name: Load environment variables from .env.ci
+        run: |
+          if [ -f .env.ci ]; then
+            export $(cat .env.ci | xargs)
+          else
+            echo ".env.ci file not found!"
+            exit 1
+          fi
+
       - name: Create Docker network for E2E tests
         run: docker network create ci_network || true
 
@@ -66,18 +78,6 @@ jobs:
 
       - name: Print current directory contents
         run: ls -la
-
-      - name: Set environment variable for CI
-        run: echo "MY_ENV_FILE=.env.ci" >> $GITHUB_ENV
-
-      - name: Load environment variables from .env.ci
-        run: |
-          if [ -f .env.ci ]; then
-            export $(cat .env.ci | xargs)
-          else
-            echo ".env.ci file not found!"
-            exit 1
-          fi
 
       - name: Run service container for E2E tests using docker-compose
         run: docker compose --env-file .env.ci up -d
